const badmintonProducts = [
  // --- DANH MỤC: VỢT (12 sản phẩm) ---
  { id: 1, name: "Yonex Astrox 100ZZ", price: 4500000, category: "vợt", weight: "4U/3U", balance: "Nặng đầu", brand: "Yonex" },
  { id: 2, name: "Victor Thruster F", price: 3800000, category: "vợt", weight: "4U", balance: "Nặng đầu", brand: "Victor" },
  { id: 3, name: "Lining Tectonic 7", price: 3500000, category: "vợt", weight: "5U", balance: "Cân bằng", brand: "Lining" },
  { id: 4, name: "Yonex Nanoflare 800", price: 4200000, category: "vợt", weight: "4U", balance: "Nhẹ đầu", brand: "Yonex" },
  { id: 5, name: "Victor DriveX 9X", price: 3600000, category: "vợt", weight: "4U", balance: "Cân bằng", brand: "Victor" },
  { id: 6, name: "Lining Bladex 800", price: 3900000, category: "vợt", weight: "3U/4U", balance: "Nhẹ đầu", brand: "Lining" },
  { id: 7, name: "Yonex Arcsaber 11 Pro", price: 4300000, category: "vợt", weight: "3U/4U", balance: "Cân bằng", brand: "Yonex" },
  { id: 8, name: "Victor Auraspeed 90K", price: 3700000, category: "vợt", weight: "3U/4U", balance: "Hơi nặng đầu", brand: "Victor" },
  { id: 9, name: "Lining Calibar 900B", price: 4100000, category: "vợt", weight: "3U", balance: "Cân bằng", brand: "Lining" },
  { id: 10, name: "Yonex Astrox 88D Pro", price: 4400000, category: "vợt", weight: "4U", balance: "Nặng đầu", brand: "Yonex" },
  { id: 11, name: "Victor Ryuga II", price: 3950000, category: "vợt", weight: "3U/4U", balance: "Rất nặng đầu", brand: "Victor" },
  { id: 12, name: "Lining Windstorm 72", price: 2800000, category: "vợt", weight: "F (72g)", balance: "Nặng đầu", brand: "Lining" },

  // --- DANH MỤC: GIÀY (12 sản phẩm) ---
  { id: 13, name: "Yonex 65Z3 White Tiger", price: 3200000, category: "giày", size: [39, 40, 41, 42], color: "Trắng", brand: "Yonex" },
  { id: 14, name: "Victor P9200TTY", price: 2900000, category: "giày", size: [40, 41, 42], color: "Vàng", brand: "Victor" },
  { id: 15, name: "Lining Saga II", price: 2500000, category: "giày", size: [38, 39, 40], color: "Xanh Dương", brand: "Lining" },
  { id: 16, name: "Yonex Aerus Z2 Men", price: 3400000, category: "giày", size: [40, 41, 42], color: "Xanh Mint", brand: "Yonex" },
  { id: 17, name: "Victor A970 Ace", price: 2700000, category: "giày", size: [39, 40, 41], color: "Đen Trắng", brand: "Victor" },
  { id: 18, name: "Lining Rogue", price: 1800000, category: "giày", size: [40, 41, 42], color: "Đỏ", brand: "Lining" },
  { id: 19, name: "Yonex Eclipsion Z3", price: 3500000, category: "giày", size: [41, 42, 43], color: "Đen", brand: "Yonex" },
  { id: 20, name: "Victor P9200II", price: 2600000, category: "giày", size: [40, 41], color: "Đỏ Đen", brand: "Victor" },
  { id: 21, name: "Lining Shadow", price: 2100000, category: "giày", size: [39, 40], color: "Xám", brand: "Lining" },
  { id: 22, name: "Yonex Comfort Z3", price: 3300000, category: "giày", size: [41, 42], color: "Đen Vàng", brand: "Yonex" },
  { id: 23, name: "Victor A780", price: 1950000, category: "giày", size: [40, 41], color: "Xanh", brand: "Victor" },
  { id: 24, name: "Lining Halberd", price: 2300000, category: "giày", size: [41, 42], color: "Trắng Cam", brand: "Lining" },

  // --- DANH MỤC: ÁO (12 sản phẩm) ---
  { id: 25, name: "Áo Yonex Đội Tuyển Nhật", price: 450000, category: "áo", size: ["M", "L", "XL"], color: "Đỏ", brand: "Yonex" },
  { id: 26, name: "Áo Victor Tournament", price: 480000, category: "áo", size: ["M", "L"], color: "Xanh Dương", brand: "Victor" },
  { id: 27, name: "Áo Lining Professional", price: 550000, category: "áo", size: ["S", "M", "L"], color: "Vàng", brand: "Lining" },
  { id: 28, name: "Áo Yonex Kỉ Niệm 75 Năm", price: 600000, category: "áo", size: ["M", "L"], color: "Trắng", brand: "Yonex" },
  { id: 29, name: "Áo Victor Cool", price: 350000, category: "áo", size: ["L", "XL"], color: "Xanh Lá", brand: "Victor" },
  { id: 30, name: "Áo Lining Đội Tuyển Trung Quốc", price: 700000, category: "áo", size: ["M", "L", "XL"], color: "Đỏ Đen", brand: "Lining" },
  { id: 31, name: "Áo Yonex Game Shirt", price: 500000, category: "áo", size: ["S", "M"], color: "Xanh Navy", brand: "Yonex" },
  { id: 32, name: "Áo Victor Đội Tuyển Hàn Quốc", price: 520000, category: "áo", size: ["M", "L", "XL"], color: "Trắng", brand: "Victor" },
  { id: 33, name: "Áo Lining Training", price: 380000, category: "áo", size: ["M", "L"], color: "Xám", brand: "Lining" },
  { id: 34, name: "Áo Ba Lỗ Yonex", price: 300000, category: "áo", size: ["L", "XL"], color: "Đen", brand: "Yonex" },
  { id: 35, name: "Áo Polo Victor", price: 420000, category: "áo", size: ["M", "L"], color: "Trắng Xanh", brand: "Victor" },
  { id: 36, name: "Áo Khoác Lining", price: 850000, category: "áo", size: ["L", "XL"], color: "Đen Vàng", brand: "Lining" },

  // --- DANH MỤC: QUẦN (12 sản phẩm) ---
  { id: 37, name: "Quần Short Yonex Pro", price: 350000, category: "quần", size: ["M", "L", "XL"], color: "Đen", brand: "Yonex" },
  { id: 38, name: "Quần Short Victor Đen", price: 320000, category: "quần", size: ["M", "L"], color: "Sọc Trắng", brand: "Victor" },
  { id: 39, name: "Quần Short Lining Thun", price: 300000, category: "quần", size: ["L", "XL"], color: "Xanh Than", brand: "Lining" },
  { id: 40, name: "Quần Short Yonex Trắng", price: 350000, category: "quần", size: ["M", "L"], color: "Trắng", brand: "Yonex" },
  { id: 41, name: "Quần Short Victor Korea", price: 400000, category: "quần", size: ["M", "L"], color: "Xanh Navy", brand: "Victor" },
  { id: 42, name: "Quần Váy Nữ Lining", price: 320000, category: "quần", size: ["S", "M"], color: "Hồng", brand: "Lining" },
  { id: 43, name: "Quần Short Yonex Logo To", price: 380000, category: "quần", size: ["L", "XL"], color: "Đen Vàng", brand: "Yonex" },
  { id: 44, name: "Quần Short Victor Pro", price: 360000, category: "quần", size: ["M", "L"], color: "Xám", brand: "Victor" },
  { id: 45, name: "Quần Short Lining Competition", price: 420000, category: "quần", size: ["M", "L"], color: "Đen", brand: "Lining" },
  { id: 46, name: "Quần Váy Nữ Yonex", price: 400000, category: "quần", size: ["S", "M"], color: "Trắng", brand: "Yonex" },
  { id: 47, name: "Quần Short Victor Game", price: 310000, category: "quần", size: ["L", "XL"], color: "Đỏ", brand: "Victor" },
  { id: 48, name: "Quần Short Lining Basic", price: 250000, category: "quần", size: ["M", "L"], color: "Xanh Dương", brand: "Lining" },

  // --- DANH MỤC: PHỤ KIỆN (12 sản phẩm) ---
  { id: 49, name: "Quấn cán Yonex AC102EX", price: 50000, category: "phụ kiện", type: "Quấn cán", brand: "Yonex" },
  { id: 50, name: "Túi vợt Victor 2 ngăn", price: 850000, category: "phụ kiện", type: "Túi đựng", brand: "Victor" },
  { id: 51, name: "Cước Lining No.1", price: 180000, category: "phụ kiện", type: "Cước", brand: "Lining" },
  { id: 52, name: "Cước Yonex BG65", price: 160000, category: "phụ kiện", type: "Cước", brand: "Yonex" },
  { id: 53, name: "Balo Victor Chuyên Dụng", price: 700000, category: "phụ kiện", type: "Balo", brand: "Victor" },
  { id: 54, name: "Chặn mồ hôi tay Lining", price: 80000, category: "phụ kiện", type: "Bảo hộ", brand: "Lining" },
  { id: 55, name: "Phấn hút mồ hôi Yonex", price: 90000, category: "phụ kiện", type: "Dụng cụ", brand: "Yonex" },
  { id: 56, name: "Túi đựng giày Victor", price: 150000, category: "phụ kiện", type: "Túi đựng", brand: "Victor" },
  { id: 57, name: "Ống cầu Lining G800", price: 450000, category: "phụ kiện", type: "Cầu lông", brand: "Lining" },
  { id: 58, name: "Bình nước Yonex 1L", price: 250000, category: "phụ kiện", type: "Dụng cụ", brand: "Yonex" },
  { id: 59, name: "Kéo cắt cước Victor", price: 120000, category: "phụ kiện", type: "Dụng cụ", brand: "Victor" },
  { id: 60, name: "Tất (Vớ) Lining", price: 60000, category: "phụ kiện", type: "Vớ", brand: "Lining" }
];